- package.json
- src/App.tsx
- yarn.lock
https://mojewideo.atlassian.net/browse/MW-127
> MW-127 Configure React Query

- src/api/subscription.ts
- src/api/user.ts
- src/data/Subscription.ts
- src/pages/User/SubscribeButton.tsx
- src/pages/User/UserDetails.tsx
- src/pages/Video/CreatorInfo.tsx
- src/pages/Video/Metadata.tsx
https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-179
Add subscribe buttons on user details page and video page
- user page
- video page
> MW-179/subscribing

- README.md
- cypress.config.ts
- cypress/e2e/register.cy.ts
- cypress/support/commands.ts
- cypress/support/e2e.ts
- cypress/tsconfig.json
- package.json
- src/components/layout/NavBar.tsx
- src/pages/Login/BaseForm.tsx
- yarn.lock
https://mojewideo.atlassian.net/browse/MW-191
Add end-to-end test in Cypress
- configure Cypress
- test registration
- test login
- test user profile
> MW-191 Test register and login in Cypress

- src/App.tsx
- src/api/video.ts
- src/components/Avatar.tsx
- src/components/video/VideoList.tsx
- src/components/video/VideoListItem.tsx
- src/components/video/VideoThumbnail.tsx
- src/pages/Homepage/index.tsx
- src/pages/Login/LoginForm.tsx
- src/pages/Login/index.tsx
- src/pages/Upload/VideoUploadForm.tsx
- src/pages/User/UserContent.tsx
- src/pages/User/UserDetails.tsx
- src/pages/User/UserDetailsEditForm.tsx
- src/pages/User/UserSubscriptions.tsx
- src/pages/User/UserVideos.tsx
- src/pages/User/index.tsx
- src/pages/Video/CreatorInfo.tsx
- src/pages/Video/Metadata.tsx
- src/pages/Video/MetadataForm.tsx
- src/pages/Video/VideoDelete.tsx
- src/pages/Video/VideoDescription.tsx
- src/pages/Video/VideoTags.tsx
- src/types/VideoTypes.ts
- src/utils/hooks.ts
- src/utils/utils.ts
- src/utils/words.ts
https://mojewideo.atlassian.net/browse/MW-170
Add videos tab to user's page
- add proper Polish grammar with numbers (1 wyświetlenie, 2 wyświetlenia, 5 wyświetleń)
- add tabs in user profile page (with routing)
- add video list to user profile page
- improve player UI
> Mw 170/user movies

- src/App.tsx
- src/api/subscription.ts
- src/components/TabRouter.tsx
- src/components/layout/Logo.tsx
- src/components/layout/NavBar.tsx
- src/components/video/VideoListItem.tsx
- src/const.ts
- src/pages/Homepage/HomepageVideos.tsx
- src/pages/Homepage/SubscribedVideos.tsx
- src/pages/Homepage/index.tsx
- src/pages/Login/index.tsx
- src/pages/Register/index.tsx
- src/pages/User/UserContent.tsx
- src/pages/Video/CreatorInfo.tsx
- src/types/VideoTypes.ts
- src/utils/utils.ts
https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-181
Add homepage tab with videos from subscribed users
- Homepage
- All videos (modified)
- Subscribed videos
> Mw 181/videos subscribed

- src/api/video.ts
- src/components/layout/AppLayout.tsx
- src/components/layout/NavBar.tsx
- src/const.ts
- src/data/VideoData.ts
- src/pages/Upload/VideoUploadForm.tsx
- src/pages/Video/CreatorInfo.tsx
- src/pages/Video/Player.tsx
- src/pages/Video/index.tsx
https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-184
Odczytywać stan przetworzenia filmu i pokazywać stosowny komunikat w playerze
- player processing view
- refactor player
> MW-184/Video processing status

- README.md
- cypress/support/commands.ts
- package.json
- src/api/user.ts
- src/components/layout/AppLoader.tsx
- src/components/layout/ContentSection.tsx
- src/const.ts
- src/pages/Login/BaseForm.tsx
- src/pages/Login/LoginForm.tsx
- src/pages/Register/RegisterForm.tsx
- src/pages/Upload/VideoUploadForm.tsx
- src/pages/User/UserDetailsEditForm.tsx
- src/pages/Video/MetadataForm.tsx
- src/pages/Video/VideoDelete.tsx
- src/types/VideoTypes.ts
- src/utils/utils.ts
https://mojewideo.atlassian.net/browse/MW-207
Display error messages from backend instead of default axios messages
> MW-207 Show error messages from backend

- .github/workflows/check_pr.yml
- package.json
https://mojewideo.atlassian.net/browse/MW-197
Add GH action for checking PRs
- check Prettier
- check ESLint
- check Typescript build
- check Vite build
> Mw 197/gh action

- src/api/donate.ts
- src/components/donate/DonateButton.tsx
- src/components/donate/WithdrawButton.tsx
- src/pages/Donate/DonateDialog.tsx
- src/pages/Donate/DonateForm.tsx
- src/pages/Donate/WithdrawDialog.tsx
- src/pages/User/UserDetails.tsx
- src/pages/User/UserInfo.tsx
- src/utils/utils.ts
https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-200
1. wysylanie donejtów
- przycisk do donejtowania obok przycisku do subowania (wszędzie gdzie występuje)
- po nacisnieciu na przycisk otwiera sie dialog z polem na kwote do wpisania
2. wyplacanie:
- przycisk obok przycisku do edycji profilu, czyli tylko na stronie usera
- otwiera się dialog z polem na kwote do wypłacenia
- strona usera
- komponent UserInfo występujący pod filmami i na listach użytkowników
> Mw 200/donates

- src/pages/User/UserDetails.tsx
ukrycie buttona do wyplacania pieniedzy jak nie jestes tworca
> Hide withdraw button on simple user's page

- src/components/NavBar/NavBar.tsx
- src/components/layout/AppLayout.tsx
https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-151
Dodać loading bar pod navbarem
- Dodać animowany loading bar
- Wyświetlić loading bar w trakcie uploadu video
> MW-151 Add loading bar on video upload

- src/pages/Donate/WithdrawDialog.tsx
- src/pages/User/UserDetails.tsx
- src/types/UserTypes.ts
> Fix displaying money

- src/api/playlist.ts
- src/pages/Homepage/HomepageVideos.tsx
- src/pages/Homepage/index.tsx
https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-115
jak w tytule
jak w tytule
> MW-115 Display recommendations on homepage

- src/api/comment.ts
- src/api/playlist.ts
- src/api/search.ts
- src/api/subscription.ts
- src/api/video.ts
- src/components/NavBar/SearchField/PlaylistSuggestion.tsx
- src/components/NavBar/SearchField/SearchField.tsx
- src/components/NavBar/SearchField/SearchSuggestion.tsx
- src/data/Subscription.ts
- src/pages/Playlist/PlaylistDelete.tsx
- src/pages/Playlist/PlaylistEditForm.tsx
- src/pages/Playlist/PlaylistInfo.tsx
- src/pages/Upload/VideoUploadForm.tsx
- src/pages/User/Playlists/NewPlaylistButton.tsx
- src/pages/User/Playlists/PlaylistList.tsx
- src/pages/User/Playlists/PlaylistTile.tsx
- src/pages/Video/AddToPlaylist.tsx
- src/pages/Video/Comment/Comment.tsx
- src/pages/Video/Comment/CommentSection.tsx
- src/types/CommentTypes.ts
- src/types/PlaylistTypes.ts
- src/types/SearchTypes.ts
- src/types/VideoTypes.ts
https://mojewideo.atlassian.net/browse/MW-218
jak w jirze
jak w jirze
> MW-218 Add REST API prefixes to data types

- src/components/NavBar/SearchField/PlaylistSuggestion.tsx
- src/components/NavBar/SearchField/SearchInput.tsx
- src/components/video/RemoveVideoFromPlaylist.tsx
- src/pages/Playlist/PlaylistDelete.tsx
- src/pages/Playlist/PlaylistEditForm.tsx
- src/pages/Playlist/PlaylistInfo.tsx
- src/pages/User/Playlists/NewPlaylistButton.tsx
- src/pages/User/UserContent.tsx
- src/pages/Video/AddToPlaylist.tsx
https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-219
Changed all "playlist*" to "grajlist*" in end user visible places
> Change GUI text from playlist* to grajlist*

- src/pages/Donate/DonateDialog.tsx
- src/pages/Donate/WithdrawDialog.tsx
- src/pages/User/UserDetails.tsx
- src/utils/numberDeclinedNouns.ts
https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-221
End of friendship with PLN, now Eurogombka is my best friend
> Change from polish złoty to eurogombkis

- src/api/video.ts
- src/components/StatusSnackbar.tsx
- src/components/donate/DonateButton.tsx
- src/components/donate/WithdrawButton.tsx
- src/pages/Donate/DonateDialog.tsx
- src/pages/Donate/WithdrawDialog.tsx
- src/pages/Playlist/PlaylistDelete.tsx
- src/pages/User/Playlists/NewPlaylistButton.tsx
- src/pages/User/UserDetails.tsx
- src/pages/User/UserDetailsEditForm.tsx
- src/pages/Video/AddToPlaylist.tsx
- src/pages/Video/MetadataForm.tsx
- src/pages/Video/VideoDelete.tsx
https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-213
jira
nie znalazlem za duzo problemow z przekierowaniami
dialogi sie zamykaja i snackbary pojawiaaja tylko gdy sukces
> Mw 213/snackbars and redirections

- src/components/layout/UploadStatusSnackbar.tsx
- src/types/VideoTypes.ts
[insert Jira task URL]
[provide short description]
- [item 1]
[paste screenshots]
> Fix failed to process state

- src/App.tsx
- src/api/user.ts
- src/components/NavBar/NavBar.tsx
- src/components/layout/AppLoader.tsx
- src/components/layout/BackendSwitcher.tsx
- src/const/index.ts
- src/data/UrlData.ts
- src/pages/SwitchBackend/OptionWrapper.tsx
- src/pages/SwitchBackend/index.tsx
- src/pages/Video/Player.tsx
https://mojewideo.atlassian.net/browse/MW-247
Backend selector
- backend selector
> MW-247 Add backend selector

- src/api/comment.ts
- src/pages/Video/Comment/Comment.tsx
- src/pages/Video/Comment/CommentSection.tsx
- src/types/CommentTypes.ts
https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-249
Comments adjustment to the altered endpoints
- Comments on other backends work now
> MW-249 Adjust comments to altered API endpoints

- src/pages/SwitchBackend/index.tsx
- src/pages/Video/Player.tsx
Bugfix: Insert current backend URL in video src
> Fix video url

- src/api/subscription.ts
niezgodność nazw parametrów ze specką
> Fix parameters names in POST and DELETE subscription

- src/api/playlist.ts
- src/pages/Search/index.tsx
- src/pages/User/Playlists/PlaylistList.tsx
- src/pages/User/Playlists/PlaylistTile.tsx
https://mojewideo.atlassian.net/browse/MW-251
Show playlist author in search results
> Mw 251/playlist author search

- src/pages/Search/DatePickerFilter.tsx
- src/pages/Search/DateRangePicker.tsx
- src/pages/Search/SearchFilters.tsx
https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-252
Dodanie walidacji do kontrolek datowych, beginDate nie może być większy niż endDate i odwrotnie
Kontrolki w filtrach wyszukiwania
bez zmian wizualnych
> Mw 252/date range picker

- src/components/NavBar/NavBar.tsx
- src/components/StatusSnackbar.tsx
- src/components/donate/DonateButton.tsx
- src/components/donate/WithdrawButton.tsx
- src/components/layout/AppLayout.tsx
- src/data/SnackbarData.ts
- src/pages/Donate/DonateDialog.tsx
- src/pages/Donate/WithdrawDialog.tsx
- src/pages/Playlist/PlaylistDelete.tsx
- src/pages/User/Playlists/NewPlaylistButton.tsx
- src/pages/User/UserDetails.tsx
- src/pages/User/UserDetailsEditForm.tsx
- src/pages/Video/AddToPlaylist.tsx
- src/pages/Video/MetadataForm.tsx
- src/pages/Video/VideoDelete.tsx
- src/types/SnackbarTypes.ts
https://mojewideo.atlassian.net/browse/MW-245
poprawka do snackbarów - pojawiają się po operacji w dialogu zakończonej sukcesem, nie znikają po kliknięciu ani po zmiany strony
dialog windows:
- wypłacanie pieniędzy
- wspieranie twórców
- usuwanie playlisty
- tworzenie playlisty
- edycja danych użytkownika
- edycja metadanych filmu
- dodawanie filmu do playlisty
- usuwanie filmu
bez zmian wizualnych
> Mw 245/snackbars

- src/App.tsx
- src/api/comment.ts
- src/api/ticket.ts
- src/components/NavBar/NavBar.tsx
- src/components/TicketButton.tsx
- src/components/video/VideoListItemMenu.tsx
- src/const/index.ts
- src/pages/Playlist/index.tsx
- src/pages/Ticket/TicketDialog.tsx
- src/pages/Ticket/TicketList.tsx
- src/pages/Ticket/TicketListItem.tsx
- src/pages/Ticket/index.tsx
- src/pages/User/UserDetails.tsx
- src/pages/User/UserInfoButtons.tsx
- src/pages/Video/Comment/Comment.tsx
- src/pages/Video/Metadata.tsx
- src/types/CommentTypes.ts
- src/types/DonateTypes.ts
- src/types/TicketTypes.ts
- src/utils/utils.ts
https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-241
Ticket list offering functionalities for admin and normal user
- jakaś strona z listą ticketów i statusem
- user moze wyswietlac swoje tickety
- admin moze dodatkowo odpowiadac
- potencjalnie uzycie komentarzy
- fajnie jakby od ticketu dalo sie przejsc linkiem do contentu zglaszanego
> Mw 241/ticket page

- src/components/TicketButton.tsx
Fix for ticket button condition
> MW-241 Ticket button condition fix

- src/const/index.ts
> MW-262 Add mov file extension

- src/pages/Upload/index.tsx
[insert Jira task URL]
[provide short description]
- [item 1]
[paste screenshots]
> Fix upload page
